### PR TITLE
Big Cleanup + a few extensions

### PR DESCRIPTION
**Pull request by CWKevo**
Since this is somewhat bigger commit, I'll let @gwillem to approve those changes. I also downloaded repo before this commit as a backup just in case. It might need adjustments to some links I might forgot about.

• Renamed every file and folder with proper capitalization to make URLs etc. look nicer and more organized.
• Checked (hopefully) every file and updated the links to match new URLs. - the "https://freeflarum.com" part was removed from the links and uses now root links instead - if FF ever decided to change domain for some reason, this will remove additional pain to update all links with the new domain, while now it auto uses the current domain.
• Added more "fancy boxes" and adjusted minor visual changes.
• Created more folders ("categories") in the documentation, so that we can navigate in the docs better and faster.
• Other small fixes and adjustments.
• Fixed links in the social logins docs.
• Moved all login docs under 1 category, since GitHub and Discord aren't really social networks.
• Added docs for FoF Default Group & User Preferences, FoF Discord Login

### CODE REVIEW

**Comment by gwillem** [comment]
Hi Kevo, sorry, had missed this one. Good work! One thing though, I'm not a fan of a) capitalization in URLs (it's not very common) and b) changing URLs altogether, because we would need redirection from the old URLs or suffer a lot of dead links. 

If you are ok with that, could you revert the renaming? Otherwise, am happy to merge.

**Comment by CWKevo** [comment]
Okay, I'll do it as soon as possible (currently I'm not home). Don't worry that you overlooked this, I have patience.

**Comment by CWKevo** [comment]
It should be done now. I had some trouble figuring out how to make GitHub pick capitalization changes in file names, as it doesn't really care, but eventually, I tricked it by deleting all files and then re-adding them again with lowercase.

I hope that this works.

**Comment by gwillem** [comment]
Woohoo!

**Pull request merged**
